apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-pack-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: starter-pack-operator
  template:
    metadata:
      labels:
        name: starter-pack-operator
    spec:
      containers:
        - name: starter-pack-operator
          image: docker.io/shurley/starterpack-operator:latest
          command:
          - starter-pack-operator
          args:
          - "--namespace"
          - "test"
          imagePullPolicy: Always
