kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: starter-pack-operator
rules:
- apiGroups:
  - starterpack.osbkit.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-starter-pack-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: starter-pack-operator
  apiGroup: rbac.authorization.k8s.io

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-starter-pack-operator-test
  namespace: test
subjects:
- kind: ServiceAccount
  name: default
  namespace: test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
